Script started on 2022-10-01 01:58:39-07:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="80" LINES="24"]
[?2004h[peiyaohe@cancun cse374]$ echo $SHELL
[?2004l/bin/bash
[?2004h[peiyaohe@cancun cse374]$ whoai[Kmi
[?2004lpeiyaohe
[?2004h[peiyaohe@cancun cse374]$ pwd
[?2004l/data/netid/peiyaohe/cse374
[?2004h[peiyaohe@cancun cse374]$ uname -a
[?2004lLinux cancun.cs.washington.edu 5.14.0-70.26.1.el9_0.x86_64 #1 SMP PREEMPT Tue Sep 20 17:53:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[?2004h[peiyaohe@cancun cse374]$ gcc --version -std=c11
[?2004lgcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[?2004h[peiyaohe@cancun cse374]$ exxit[K[K[K[Ki[Kxit
[?2004lexit

Script done on 2022-10-01 01:59:46-07:00 [COMMAND_EXIT_CODE="0"]
